### ISSUE TITLE
How to build a custom Adapter

### ISSUE THREAD

**Issue by vasilakisfil** [itsfadnis/jsonapi-client#30]
That's a very interesting little library! I suggest that you add some documentation (and apply any code changes needed) to allow other adapters to be used with the rest infrastructure of your library so that it's not JSON:API only specific. Keep up the good work!

**Comment by itsfadnis** [comment]
Thanks for the feedback @vasilakisfil! This library was built specifically to be [JSON:API](https://jsonapi.org/) compliant.

However I do get your point. It would definitely be possible to keep the rest infrastructure & json serialization/deserialization independent of each other. But that would involve some significant changes. Mainly to allow the [Model#serialize()](https://github.com/itsfadnis/jsonapi-client/blob/master/src/model.js#L201) & [Model.deserialize(response)](https://github.com/itsfadnis/jsonapi-client/blob/master/src/model.js#L201) to be configurable. There is some more [JSON:API](https://jsonapi.org/) specific code present inside the [Model](https://github.com/itsfadnis/jsonapi-client/blob/master/src/model.js) which would have to be refactored.

Any suggestions/code would be welcome. Will have a look at this when I have some bandwidth.

✌️
