### ISSUE TITLE
Any chance for declarations or @types

### ISSUE THREAD

**Issue by ishoshani** [itsfadnis/jsonapi-client#65]
This library looks like a really nice way to interface with json:api, and I see you just migrated the codebase to typescript! I'd like to integrate it with TS projects, but the published version doesn't have any class declarations published, unless I'm missing something?

**Comment by itsfadnis** [comment]
@ishoshani Thanks for your interest!

You're right, I completely forgot about writing class declarations 🤦.
I'm taking this up on priority & will open a PR very soon. Keep an eye out :)
